[WIP] Layout update
rgllm/awesome-portugal-data pull request #11
Opened 2020-06-18 15:23 UTC by ptalmeida

Refere #9 ,abro aqui o PR WIP para continuarmos a discussão da implementação.

Testei como tinha ficado definido mas não me pareceu bem utilizar **Autenticação** ✔️ / ❌ pois parece-me um pouco uma dupla negação (no caso do ❌ o acesso é livre, mas o emoji é "negativo").

Experimentei com **Acesso** e com os cadeados mas no MacOs pelo menos parece-me muito difícil de diferenciar entre os dois. Talvez seja melhor **Aberto** ou algo semelhante e permanecer com o ✔️ / ❌. Sugestões?

Meti também as entradas por ordem alfabética e deixei um ❓ numa entrada que parece estar em baixo por agora.

2020-06-18 18:08 UTC, waldyrious commented
Gosto da ideia de "Aberto", isso estabelece uma expectativa de abertura em vez do contrário 👍

Quanto a ✔️, não seria melhor ✅? O ❌ [tende a ser vermelho](https://emojipedia.org/cross-mark/), por isso era fixe usar algo que seja [representado como verde](https://emojipedia.org/check-mark-button/https://emojipedia.org/check-mark-button/) na maior parte dos casos, em vez do primeiro em que [o verde é uma minoria](https://emojipedia.org/check-mark/) :)

2020-06-19 10:19 UTC, ptalmeida commented
Mais uns comentários:

- Ficar como Aberto também me pareceu confuso, porque há APIs onde tem de se pedir um token, mas que este é dado automaticamente, e APIs onde à quotas de uso gratuito.
- Deveríamos manter feeds RSS?
- Quando é simplesmente exposto o ficheiro pus ![](https://img.shields.io/badge/Webservice-blue), que acham?
- Removi duas entradas redundantes e uma que não funcionava.

2020-06-19 10:28 UTC, rgllm commented
@ptalmeida por pontos:

- Assumo que essa é a razão da distinção entre 🔒 e 🔒🔒, certo?
- Relativamente ao RSS acho que sim, é mais uma forma possível de consumir dados.
- Concordo.
- 👍

2020-06-20 15:26 UTC, rgllm commented
Grande trabalho @ptalmeida 🎉

2020-06-22 21:12 UTC, ptalmeida commented
Mais duas alterações feitas, a [segunda](https://github.com/rgllm/awesome-portugal-data/pull/11/commits/9e6790642c75db1af4823f3f056f73a6ac56c4f5), um pouco mais de gosto, inspirada no header [deste](https://github.com/marmelo/tech-companies-in-portugal) repo.

Caso aprovem por mim está pronto para o merge!

2020-06-23 13:35 UTC, rgllm requested changes
A única coisa que tenho dúvidas é na legenda. Acho que deviamos separar da descrição.

2020-06-23 13:35 UTC, rgllm commented on README.md
> +APIs marcados com ✅ não requerem tokens de acesso.
@ptalmeida a legenda podia ficar separada disto

2020-06-23 14:29 UTC, ptalmeida commented on README.md
> +APIs marcados com ✅ não requerem tokens de acesso.
Como sugeres que fique em relação à descrição?

Eu pessoalmente preferiria deixar assim, talvez com um paragrafo entre a descrição e a legenda, e depois fazer outro PR a passar tudo para Inglês, como aqui https://github.com/marmelo/tech-companies-in-portugal.  
  
Como está tem uma  mistura de inglês e português que não é muito útil a quem não fale português que a queira usar.

2020-06-23 17:38 UTC, rgllm commented on README.md
> +APIs marcados com ✅ não requerem tokens de acesso.
Vou então dar merge deste e depois eu faço um com a minha sugestão para veres.

2020-06-23 17:38 UTC, rgllm approved these changes
🚀

2020-06-23 17:39 UTC, merged